<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>focus</string>
	</array>
	<key>name</key>
	<string>Focus</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#alias_translator</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#datadef_translator</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#importexport_translator</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#include_translator</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#local_translator</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#magic_translator</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#screen_translator</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#screencomponent_translator</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#screenrecord_translator</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#screenpage_translator</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#other_translator</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>alias_translator</key>
		<dict>
			<key>begin</key>
			<string>^(#Alias)\b\s*\n?</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.translator.header.focus</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.translator.focus</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Translator -</string>
			<key>end</key>
			<string>(?=^#)</string>
			<key>name</key>
			<string>meta.translator.alias.focus</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.keyword.focus</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.value.attribute.focus meta.alias.defined.focus constant.other.alias.focus</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^ *(:Alias) +([^()
	]+?) *$
?</string>
					<key>name</key>
					<string>meta.keyword.alias.focus</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#attribute_line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#translator_continuation</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<key>attribute_line</key>
		<dict>
			<key>begin</key>
			<string>^ +([A-Za-z0-9]+) *</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.attribute.focus</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>meta.value.attribute.focus</string>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>meta.attribute.focus</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#externalized-list</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-list</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#code-region</string>
				</dict>
			</array>
		</dict>
		<key>blank-line-error</key>
		<dict>
			<key>match</key>
			<string>^ *\n</string>
			<key>name</key>
			<string>invalid.illegal.blank-line.fs</string>
		</dict>
		<key>break</key>
		<dict>
			<key>begin</key>
			<string>@Break\(</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>support.function.focus</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Break</string>
			<key>contentName</key>
			<string>meta.function.arguments.translate-time.focus</string>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>support.function.focus</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.focus meta.debug.focus</string>
		</dict>
		<key>called_alias</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.other.alias.focus</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>source.args.alias.focus</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.other.alias.focus</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Called Alias</string>
			<key>match</key>
			<string>(@@[^\n()]+?\()([^\n()]*?)(\))</string>
			<key>name</key>
			<string>meta.alias.called.focus</string>
		</dict>
		<key>code-keyword</key>
		<dict>
			<key>begin</key>
			<string>^ *((:Code) +([^
()	]+?)) *$
?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.subroutine.header.fs</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.keyword.focus</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>meta.value.keyword.focus entity.name.subroutine.fs</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Code Member Keyword</string>
			<key>end</key>
			<string>;</string>
			<key>name</key>
			<string>meta.keyword.code.focus meta.subroutine.fs</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#code-region</string>
				</dict>
			</array>
		</dict>
		<key>code-region</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#externalized-list-separator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#illegal-line-start</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#illegal-line-end</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-list</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#called_alias</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#break</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#sortrecords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#mat_function</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.variable.other.local.fs constant.numeric</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>FS Local Variable</string>
					<key>match</key>
					<string>(?&lt;!@|\.)\b([A-Z])\b</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.variable.other.global.fs constant.numeric</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>FS Global Variable</string>
					<key>match</key>
					<string>(?&lt;!@|\.)\b([a-z])\b</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#control_flow</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#illegal-spaces</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.function.listset.number.upper.fs</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Magic Upper Listset Function</string>
					<key>match</key>
					<string>@[A-Z](\d+)</string>
					<key>name</key>
					<string>meta.function.fs meta.function.listset.upper.fs</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.function.listset.number.lower.fs</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Magic Lower Listset Function</string>
					<key>match</key>
					<string>@[a-z](\d+)</string>
					<key>name</key>
					<string>meta.function.fs meta.function.listset.lower.fs</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Magic Function</string>
					<key>match</key>
					<string>@\p{Alpha}{2}</string>
					<key>name</key>
					<string>meta.function.fs</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#illegal-block-start</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Comparison operators</string>
					<key>match</key>
					<string>@?~?(\!|\&amp;|\=|\&lt;|\&gt;)</string>
					<key>name</key>
					<string>keyword.operator.comparison.fs</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Arithmetic operators</string>
					<key>match</key>
					<string>@?~?(\+|\-|\/|\*|\\)</string>
					<key>name</key>
					<string>keyword.operator.arithmetic.fs</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Other operators</string>
					<key>match</key>
					<string>@?~?(\#|\$|\%|\:|\|)</string>
					<key>name</key>
					<string>keyword.operator.other.fs</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Assignment operators</string>
					<key>match</key>
					<string>\^(?=[\{A-Za-z])</string>
					<key>name</key>
					<string>keyword.operator.assignment.fs</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Illegal assignment</string>
					<key>match</key>
					<string>\^(?=[^\{A-Za-z])</string>
					<key>name</key>
					<string>invalid.illegal.assignment.fs</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#blank-line-error</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#errant-bracket</string>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>begin</key>
			<string>(//)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.fs</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$\n?|(?=\p{Cntrl}\|)</string>
			<key>name</key>
			<string>comment.line.double-slash.fs</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>comment.line.double-slash.header.fs</string>
						</dict>
					</dict>
					<key>match</key>
					<string>:Doc\s+(\w+\s?\w*)</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Purpose</string>
					<key>match</key>
					<string>(?i:((side )?effects?|actions?|desc(r(iption)?)?|assumes?|pre(conditions?)?|s/e|bugs?|warning)):</string>
					<key>name</key>
					<string>comment.line.double-slash.header.fs</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Arguments</string>
					<key>match</key>
					<string>(?i:(in(put)?s?|arg(ument)?s?|val(ues)?)):</string>
					<key>name</key>
					<string>comment.line.double-slash.header.fs</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Variables</string>
					<key>match</key>
					<string>(?i:((local )?var(iable)?s?|locals?)):</string>
					<key>name</key>
					<string>comment.line.double-slash.header.fs</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Sets</string>
					<key>match</key>
					<string>(?i:((upper|lower)?(case)? ?(list)?sets?)):</string>
					<key>name</key>
					<string>comment.line.double-slash.header.fs</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Returns</string>
					<key>match</key>
					<string>(?i:(out(put)?s?|ret(urn)?s?)):</string>
					<key>name</key>
					<string>comment.line.double-slash.header.fs</string>
				</dict>
			</array>
		</dict>
		<key>conditional-line</key>
		<dict>
			<key>begin</key>
			<string>(?=[^\s/])</string>
			<key>comment</key>
			<string>A condition and action within a DO loop or IF statement</string>
			<key>end</key>
			<string>((;)|(?=}))</string>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.separator.semicolon.fs</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.control.flow.check.fs</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>Too many spaces in a conditional</string>
					<key>match</key>
					<string>(?&lt;=\S)\ {2,}(?=[^\s/])</string>
					<key>name</key>
					<string>invalid.illegal.spaces.fs</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>legal space</string>
					<key>match</key>
					<string>(?&lt;=\S)\ (?=[^\s/])</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#code-region</string>
				</dict>
			</array>
		</dict>
		<key>control_flow</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>@?IF({)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.if.begin.fs</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Conditional: IF{},@IF{}</string>
					<key>end</key>
					<string>}</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.if.end.fs</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.control.flow.if.fs</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#illegal-line-start</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#conditional-line</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#blank-line-error</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>@?DO({)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.do.begin.fs</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>DO Loop: DO{},@DO{}</string>
					<key>end</key>
					<string>}</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.do.end.fs</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.control.flow.do.fs</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#illegal-line-start</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#conditional-line</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#blank-line-error</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>@(\[)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.loop.begin.fs</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Apply-To-All: @[]</string>
					<key>end</key>
					<string>\]</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.loop.end.fs</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.control.flow.loop.fs</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#code-region</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\[</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.pass-through.begin.fs</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Pass-through: []</string>
					<key>end</key>
					<string>\]</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.pass-through.end.fs</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.control.flow.pass-through.fs</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#code-region</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>@?(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.concatenate.begin.fs</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Concatenation: (),@()</string>
					<key>end</key>
					<string>\)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.concatenate.end.fs</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.control.flow.concatenate.fs</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>,</string>
							<key>name</key>
							<string>punctuation.definition.separator.comma.fs</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#code-region</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(@(\{)|(\{)(?=\})|(\{))</string>
					<key>beginCaptures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.list.begin.fs</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.list.begin.fs meta.empty-list.fs</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.list.begin.fs</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Build List: {},@{}</string>
					<key>end</key>
					<string>(((?&lt;=[^@]\{)\})|\})</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.list.end.fs</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.empty-list.fs</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.control.flow.list.fs</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>,</string>
							<key>name</key>
							<string>punctuation.definition.separator.comma.fs</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#code-region</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>datadef_translator</key>
		<dict>
			<key>begin</key>
			<string>^(#DataDef)\b\s*\n?</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.translator.header.focus</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.translator.focus</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Translator -</string>
			<key>end</key>
			<string>(?=^#)</string>
			<key>name</key>
			<string>meta.translator.datadef.focus</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#object_keyword</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#index_keyword</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#object_attribute</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keyword_line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#attribute_line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#translator_continuation</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<key>errant-bracket</key>
		<dict>
			<key>comment</key>
			<string>Extraneous brackets</string>
			<key>match</key>
			<string>[})\]].*$\n?</string>
			<key>name</key>
			<string>invalid.illegal.bracket.fs</string>
		</dict>
		<key>externalized-list</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\p{Cntrl}{</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.externalized-list.begin.focus keyword.other.externalized-list.focus</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Externalized list in dictionary source</string>
					<key>end</key>
					<string>\p{Cntrl}}</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.externalized-list.end.focus keyword.other.externalized-list.focus</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.externalized-list.focus</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#externalized-list-separator</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#code-region</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.externalized-list.nil-list.focus keyword.other.externalized-list.focus</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Externalized nil list in dictionary source</string>
					<key>match</key>
					<string>\p{Cntrl}~</string>
					<key>name</key>
					<string>meta.externalized-list.nil-list.focus</string>
				</dict>
			</array>
		</dict>
		<key>externalized-list-separator</key>
		<dict>
			<key>comment</key>
			<string>Externalized list separator</string>
			<key>match</key>
			<string>\p{Cntrl}\|</string>
			<key>name</key>
			<string>punctuation.definition.externalized-list.separator.focus keyword.other.externalized-list.focus</string>
		</dict>
		<key>illegal-block-start</key>
		<dict>
			<key>comment</key>
			<string>Starting a new code block before the previous one is finished</string>
			<key>match</key>
			<string>:(Code|List)\s*.*</string>
			<key>name</key>
			<string>invalid.illegal.block-start.fs</string>
		</dict>
		<key>illegal-line-end</key>
		<dict>
			<key>match</key>
			<string>@\s*($|(?=//.*$))</string>
			<key>name</key>
			<string>invalid.illegal.line-end.fs</string>
		</dict>
		<key>illegal-line-start</key>
		<dict>
			<key>match</key>
			<string>^ *(((:|#)(?!Code))|(/[^/]))</string>
			<key>name</key>
			<string>invalid.illegal.line-start.fs</string>
		</dict>
		<key>illegal-spaces</key>
		<dict>
			<key>comment</key>
			<string>Disallowed spacing</string>
			<key>match</key>
			<string>(?&lt;=\S)\ +(?!\s|//|$)</string>
			<key>name</key>
			<string>invalid.illegal.spaces.fs</string>
		</dict>
		<key>importexport_translator</key>
		<dict>
			<key>begin</key>
			<string>^(#ImportExport)\b\s*\n?</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.translator.header.focus</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.translator.focus</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=^#)</string>
			<key>name</key>
			<string>meta.translator.importexport.focus</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#object_keyword</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#index_keyword</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keyword_line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#object_attribute</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#attribute_line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#translator_continuation</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<key>include_translator</key>
		<dict>
			<key>begin</key>
			<string>^(#Include)\b\s*\n?</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.translator.header.focus</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.translator.focus</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=^#)</string>
			<key>name</key>
			<string>meta.translator.include.focus</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#keyword_line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#attribute_line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<key>index_keyword</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.keyword.focus</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>meta.value.keyword.focus variable.parameter.object.focus</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^ *(:(Index|IndexKey)) +([\w.]+) *$\n?</string>
			<key>name</key>
			<string>meta.keyword.object.focus</string>
		</dict>
		<key>keyword-string-list</key>
		<dict>
			<key>begin</key>
			<string>(\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.keyword-string-list.fs punctuation.definition.string-list.begin.fs</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>List of strings used in :List</string>
			<key>end</key>
			<string>(\})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.keyword-string-list.fs punctuation.definition.string-list.end.fs</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.keyword-string-list.fs</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keyword-string-list</string>
				</dict>
				<dict>
					<key>match</key>
					<string>|</string>
					<key>name</key>
					<string>keyword.operator.list-separator.fs punctuation.definition.separator.bar.fs</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#blank-line-error</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[^{}|]</string>
					<key>name</key>
					<string>string.unquoted.string-list.fs</string>
				</dict>
			</array>
		</dict>
		<key>keyword_line</key>
		<dict>
			<key>begin</key>
			<string>^ *(:\p{Alpha}+) *</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.keyword.focus</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Keyword line</string>
			<key>contentName</key>
			<string>meta.value.keyword.focus</string>
			<key>end</key>
			<string>\s*$\n?</string>
			<key>name</key>
			<string>meta.keyword.focus</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#externalized-list</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-list</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#code-region</string>
				</dict>
			</array>
		</dict>
		<key>list-keyword</key>
		<dict>
			<key>begin</key>
			<string>^ *((:List) +([^
()	]+?)) *$
?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.list.header.fs</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.keyword.focus</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>meta.value.keyword.focus entity.name.list.fs</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>List Member Keyword</string>
			<key>end</key>
			<string>(?=^$|^\s*:)</string>
			<key>name</key>
			<string>meta.keyword.list.focus meta.list.fs</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keyword-string-list</string>
				</dict>
			</array>
		</dict>
		<key>local_translator</key>
		<dict>
			<key>begin</key>
			<string>^(#Locals)\b\s*\n?</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.translator.header.focus</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.translator.focus</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=#)</string>
			<key>name</key>
			<string>meta.translator.local.focus</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.keyword.focus</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.value.keyword.focus variable.other.local.focus</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^ *(:Name) +([\w._-]+) *$\n?</string>
					<key>name</key>
					<string>meta.keyword.local-name.focus</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<key>magic_translator</key>
		<dict>
			<key>begin</key>
			<string>^(#Magic)\b\s*\n?</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.translator.header.focus</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.translator.focus</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Translators</string>
			<key>end</key>
			<string>(?=^#)</string>
			<key>name</key>
			<string>meta.translator.magic.focus</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#code-keyword</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#list-keyword</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.keyword.focus</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.value.keyword.focus entity.name.subroutine.fs</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^(:EntryPoint) +([^
()	]+?) *$
?</string>
					<key>name</key>
					<string>meta.keyword.entrypoint.focus</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.attribute.focus</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.value.keyword.focus meta.alias.defined.focus constant.other.alias.focus</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^ *(Alias) +([^
()	]+?) *$
?</string>
					<key>name</key>
					<string>meta.attribute.alias.focus</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#translator_continuation</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<key>mat_function</key>
		<dict>
			<key>begin</key>
			<string>@\p{Alpha}{3,}\(</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>support.function.focus</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Focus Function</string>
			<key>contentName</key>
			<string>meta.function.arguments.translate-time.focus</string>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>support.function.focus</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.focus</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.subroutine.fs</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?&lt;=CallSub\(|CallList\(|CodeMemberNumber\(|BatchesToStackWhile\()([^\n()\t]+)</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.object.focus</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.subroutine.fs</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?&lt;=FileBatchesWhile\()([\w._-]+)(,[^\n()\t]+)</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=(Get|Put)Local\()[\w._-]+</string>
					<key>name</key>
					<string>variable.other.local.focus</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=(Get|Put)SystemVariable\()[\w._-]+</string>
					<key>name</key>
					<string>variable.other.system.focus</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=(Get|Put)StateVariable\()[\w._-]+</string>
					<key>name</key>
					<string>variable.other.state.focus</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=OID\(|RID\(|RIDs\(|OIDs\()[\w._-]+</string>
					<key>name</key>
					<string>variable.parameter.object.focus</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=CallStructuredImport\(|CallStructuredCreate\(|CallStructuredCopyLocal\(|CallStructuredExport\(|CallStructuredExportTxn\(|CallStructuredFlush\(|CallStructuredSubmit\(|CallStructuredPurge\()[\w._-]+</string>
					<key>name</key>
					<string>variable.parameter.object.focus</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=ObjectLong\(|ProcessLong\()[\w._-]+</string>
					<key>name</key>
					<string>variable.parameter.object.focus</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.object.focus</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?&lt;=CallStructuredImportAdditional\()([\w._-]+),[\w._-]+</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=Field\(|Key\(|FieldExternal\(|KeyExternal\(|ElementLabel\()[\w._-]+</string>
					<key>name</key>
					<string>variable.parameter.object.focus</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=File\(|Record\(|Records\(|FileCx\(|RecordCx\(|RecordsCx\(|Object\(|Objects\(|ObjectClass\()[\w._-]+</string>
					<key>name</key>
					<string>variable.parameter.object.focus</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=LockSystemInfo\()[\w._-]+</string>
					<key>name</key>
					<string>variable.parameter.object.focus</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=IndexLookup\(|Index\(|IndexEntry\(|IndexLookupCx\(|IndexLookupResults\(|IndexEntries\()[\w._-]+</string>
					<key>name</key>
					<string>variable.parameter.object.focus</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=FullyInMemory\()[\w._-]+</string>
					<key>name</key>
					<string>variable.parameter.object.focus</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=NextURN\()[\w._-]+</string>
					<key>name</key>
					<string>variable.parameter.object.focus</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=NoDuplicateCheck\()[\w._-]+</string>
					<key>name</key>
					<string>variable.parameter.object.focus</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=ToOID\(|ToOIDCx\()[\w._-]+</string>
					<key>name</key>
					<string>variable.parameter.object.focus</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=RecordsChanged\(|RecordChanged\(|ObjectChanged\(|RecordCreated\(|RecordsCreated\()[\w._-]+</string>
					<key>name</key>
					<string>variable.parameter.object.focus</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=RecordTag\()[\w._-]+</string>
					<key>name</key>
					<string>variable.parameter.object.focus</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=ObjectSnapshot\(|SnapshotExists\()[\w._-]+</string>
					<key>name</key>
					<string>variable.parameter.object.focus</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=FlushWithTxn\()[\w._-]+</string>
					<key>name</key>
					<string>variable.parameter.object.focus</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#control_flow</string>
				</dict>
			</array>
		</dict>
		<key>object_attribute</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.attribute.focus</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.value.attribute.focus variable.parameter.object.focus</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>M-AT Attribute</string>
			<key>match</key>
			<string>^ *(Name|File|Class|Record|Index|Pointer) +([\w.]+) *$\n?</string>
			<key>name</key>
			<string>meta.attribute.object.focus</string>
		</dict>
		<key>object_keyword</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.keyword.focus</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>meta.value.keyword.focus variable.parameter.object.focus</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^ *(:(Object|Record|File|Field|Key|Element)) +([\w.]+) *$\n?</string>
			<key>name</key>
			<string>meta.keyword.object.focus</string>
		</dict>
		<key>other_translator</key>
		<dict>
			<key>begin</key>
			<string>^(#\p{Alpha}+) *$\n?</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.translator.header.focus</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.translator.focus</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=^#)</string>
			<key>name</key>
			<string>meta.translator.other.focus</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#keyword_line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#attribute_line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#translator_continuation</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<key>screen_translator</key>
		<dict>
			<key>begin</key>
			<string>^(#Screen)\b\s*\n?</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.translator.header.focus</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.translator.focus</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=^#)</string>
			<key>name</key>
			<string>meta.translator.screen.focus</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#keyword_line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#object_attribute</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#attribute_line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#translator_continuation</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<key>screencomponent_translator</key>
		<dict>
			<key>begin</key>
			<string>^(#ScreenComponent)\b\s*\n?</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.translator.header.focus</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.translator.focus</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=^#)</string>
			<key>name</key>
			<string>meta.translator.screencomponent.focus</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.keyword.focus</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.value.keyword.focus meta.elementset-name.focus</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^ *(:ElementSet) +([^
()	]+?) *$
?</string>
					<key>name</key>
					<string>meta.keyword.elementset.focus</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.attribute.focus</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.value.attribute.focus</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^ *(Name) +([^
()	]+?) *$
?</string>
					<key>name</key>
					<string>meta.attribute.focus</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#object_keyword</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keyword_line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#object_attribute</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#attribute_line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#translator_continuation</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<key>screenpage_translator</key>
		<dict>
			<key>begin</key>
			<string>^(#ScreenPage)\b\s*$\n?</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.translator.header.focus</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.translator.focus</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=^#)</string>
			<key>name</key>
			<string>meta.translator.screenpage.focus</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#keyword_line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#attribute_line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<key>screenrecord_translator</key>
		<dict>
			<key>begin</key>
			<string>^(#ScreenRecord)\b\s*$\n?</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.translator.header.focus</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.translator.focus</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=^#)</string>
			<key>name</key>
			<string>meta.translator.screenrecord.focus</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#object_keyword</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keyword_line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#attribute_line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#translator_continuation</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<key>sortrecords</key>
		<dict>
			<key>begin</key>
			<string>@SortRecords\(</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>support.function.focus</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Special handling for the @SortRecords function</string>
			<key>contentName</key>
			<string>meta.function.arguments.translate-time.focus</string>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>support.function.focus</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.focus</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&lt;=SortRecords\()[\w._-]+</string>
					<key>name</key>
					<string>variable.parameter.object.focus</string>
				</dict>
				<dict>
					<key>match</key>
					<string>,[AD](?=\))</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#code-region</string>
				</dict>
			</array>
		</dict>
		<key>string</key>
		<dict>
			<key>begin</key>
			<string>(")</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.fs</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>double quoted string</string>
			<key>end</key>
			<string>((?&lt;=")(")|")|(\n)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.fs</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.nil.fs</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.unclosed-string.fs</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.single-line.fs</string>
		</dict>
		<key>string-list</key>
		<dict>
			<key>begin</key>
			<string>(`)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.string-list.fs punctuation.definition.string-list.begin.fs</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>String List</string>
			<key>end</key>
			<string>(')</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.string-list.fs punctuation.definition.string-list.end.fs</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.string-list.fs</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string-list</string>
				</dict>
				<dict>
					<key>match</key>
					<string>,</string>
					<key>name</key>
					<string>keyword.operator.comma.fs punctuation.definition.separator.comma.fs</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[^,'`]</string>
					<key>name</key>
					<string>string.unquoted.string-list.fs</string>
				</dict>
			</array>
		</dict>
		<key>translator_continuation</key>
		<dict>
			<key>begin</key>
			<string>^ *(--&gt;) +</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.attribute.focus</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>meta.value.attribute.focus</string>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>meta.translator.continuation.focus</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-list</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#code-region</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.focus</string>
	<key>uuid</key>
	<string>da222f5a-4cec-4bcd-82ec-93cedfde55b9</string>
</dict>
</plist>
