<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>focus</string>
		<string>fs</string>
	</array>
	<key>foldingStartMarker</key>
	<string>^Code:.+$</string>
	<key>foldingStopMarker</key>
	<string>^;$</string>
	<key>name</key>
	<string>M-AT</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string_list</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#alias_translator</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#datadef_translator</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#importexport_translator</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#include_translator</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#local_translator</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#magic_translator</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#screen_translator</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#screencomponent_translator</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#screenrecord_translator</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#screenpage_translator</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#other_translator</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#code_keyword</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>alias_translator</key>
		<dict>
			<key>begin</key>
			<string>^(#Alias)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>translator.source.m-at</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=^#)</string>
			<key>name</key>
			<string>alias.translator.source.m-at</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.source.m-at</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>alias.source.m-at</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^ *(:Alias) +([^()
	]+?) *$</string>
					<key>name</key>
					<string>alias.keyword.source.m-at</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#attribute_line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#translator_continuation</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<key>attribute_line</key>
		<dict>
			<key>begin</key>
			<string>^ +([A-Za-z]+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>attribute.source.m-at</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>other.attribute.source.m-at</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string_list</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#code_region</string>
				</dict>
			</array>
		</dict>
		<key>break</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>arguments.m-at</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Break</string>
			<key>match</key>
			<string>@Break(Reset)?\(([^
\(\)]*)\)</string>
			<key>name</key>
			<string>debug.m-at</string>
		</dict>
		<key>called_alias</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>alias.source.m-at</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>args.alias.source.m-at</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Called Alias</string>
			<key>match</key>
			<string>@@[^
()]+?\(([^
()]*?)\)</string>
		</dict>
		<key>code_keyword</key>
		<dict>
			<key>begin</key>
			<string>^ *((:Code) +([^
()	]+?)) *$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>subroutine.header.source.m-at</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.source.m-at</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>subroutine.name</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Code Member</string>
			<key>end</key>
			<string>;</string>
			<key>name</key>
			<string>codeblock.source.m-at</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#code_region</string>
				</dict>
			</array>
		</dict>
		<key>code_region</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string_list</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#called_alias</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#break</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#mat_function</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#focus_var</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#control_flow</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#focus_function</string>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>begin</key>
			<string>//</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>comment.line</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>comment.header</string>
						</dict>
					</dict>
					<key>match</key>
					<string>:Doc\s+(\w+\s?\w*)</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(IN|OUT|VARS|EFFECT|Input|INPUT|Output|OUTPUT|Actions|Descr|DESCR|Assume|Vars|PRE|DESC|Desc|In|Out|Sets|Bugs|Arg|Val|Var|S/E|LOCALS|RETURN|ASSUMES|WARNING|DESCRIPTION|ARGUMENTS|RESULTS|VARIABLES|UPPERSETS|SETS):</string>
					<key>name</key>
					<string>comment.header</string>
				</dict>
			</array>
		</dict>
		<key>control_flow</key>
		<dict>
			<key>begin</key>
			<string>(@?(IF|DO)\{|@?\{)</string>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>control.flow</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#code_region</string>
				</dict>
			</array>
		</dict>
		<key>datadef_translator</key>
		<dict>
			<key>begin</key>
			<string>^(#DataDef)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>translator.source.m-at</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=^#)</string>
			<key>name</key>
			<string>datadef.translator.source.m-at</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#object_keyword</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#object_attribute</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keyword_line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#attribute_line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#translator_continuation</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<key>focus_function</key>
		<dict>
			<key>comment</key>
			<string>Magic Function</string>
			<key>match</key>
			<string>(@(\p{Alpha}{2}|\p{Alpha}\d{1,3})|\bDO\b|\bIF\b)</string>
			<key>name</key>
			<string>focus.function</string>
		</dict>
		<key>focus_var</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>var.source.m-at</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Focus Variable</string>
			<key>match</key>
			<string>(?&lt;!@|\.)\b([A-Z])\b</string>
		</dict>
		<key>importexport_translator</key>
		<dict>
			<key>begin</key>
			<string>^(#ImportExport)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>translator.source.m-at</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=^#)</string>
			<key>name</key>
			<string>importexport.translator.source.m-at</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#object_keyword</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keyword_line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#object_attribute</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#attribute_line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#translator_continuation</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<key>include_translator</key>
		<dict>
			<key>begin</key>
			<string>^(#Include)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>translator.source.m-at</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=^#)</string>
			<key>name</key>
			<string>include.translator.source.m-at</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#keyword_line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#attribute_line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<key>keyword_line</key>
		<dict>
			<key>begin</key>
			<string>^ *(:\p{Alpha}+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.m-at</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Keyword line</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>other.keyword.source.m-at</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string_list</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#code_region</string>
				</dict>
			</array>
		</dict>
		<key>list_keyword</key>
		<dict>
			<key>begin</key>
			<string>^ *((:List) +([^
()	]+?)) *$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>list.header.source.m-at</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.source.m-at</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>subroutine.name</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>List Member</string>
			<key>end</key>
			<string>(?=:)</string>
			<key>name</key>
			<string>listblock.source.m-at</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>String</string>
					<key>match</key>
					<string>[\w\W&amp;&amp;[^\}^\{^|^
]]*</string>
					<key>name</key>
					<string>string</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>List Delimiter</string>
					<key>match</key>
					<string>[\}\{|]</string>
					<key>name</key>
					<string>m-at.function</string>
				</dict>
			</array>
		</dict>
		<key>local_translator</key>
		<dict>
			<key>begin</key>
			<string>^(#Locals)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>translator.source.m-at</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=#)</string>
			<key>name</key>
			<string>local.translator.source.m-at</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.source.m-at</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>local.source.m-at</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^ *(:Name) +([\w._-]+) *$</string>
					<key>name</key>
					<string>name.keyword.source.m-at</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<key>magic_translator</key>
		<dict>
			<key>begin</key>
			<string>^(#Magic)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>translator.source.m-at</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Translators</string>
			<key>end</key>
			<string>(?=^#)</string>
			<key>name</key>
			<string>magic.translator.source.m-at</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#code_keyword</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#list_keyword</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.source.m-at</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>subroutine.name</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^(:EntryPoint) +([^
()	]+?) *$</string>
					<key>name</key>
					<string>entrypoint.keyword.source.m-at</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>attribute.source.m-at</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>alias.source.m-at</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^ *(Alias) +([^
()	]+?) *$</string>
					<key>name</key>
					<string>alias.attribute.source.m-at</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#translator_continuation</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<key>mat_function</key>
		<dict>
			<key>begin</key>
			<string>@\p{Alpha}{3,}\(</string>
			<key>end</key>
			<string>(\))</string>
			<key>name</key>
			<string>m-at.function</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>subroutine.name</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?&lt;=CallSub\(|CallList\(|CodeMemberNumber\(|BatchesToStackWhile\()([^\n()\t]+)</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>object.source.m-at</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>subroutine.name</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?&lt;=FileBatchesWhile\()([\w._-]+)(,[^\n()\t]+)</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=(Get|Put)Local\()[\w._-]+</string>
					<key>name</key>
					<string>local.source.m-at</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=OID\(|RID\(|RIDs\(|OIDs\()[\w._-]+</string>
					<key>name</key>
					<string>object.source.m-at</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=CallStructuredImport\(|CallStructuredCreate\(|CallStructuredCopyLocal\(|CallStructuredExport\(|CallStructuredExportTxn\(|CallStructuredFlush\(|CallStructuredSubmit\(|CallStructuredPurge\()[\w._-]+</string>
					<key>name</key>
					<string>object.source.m-at</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=ObjectLong\(|ProcessLong\()[\w._-]+</string>
					<key>name</key>
					<string>object.source.m-at</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>object.source.m-at</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>argument.m-at</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?&lt;=CallStructuredImportAdditional\()([\w._-]+)(,[\w._-]+)</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=Field\(|Key\(|FieldExternal\(|KeyExternal\(|ElementLabel\()[\w._-]+</string>
					<key>name</key>
					<string>object.source.m-at</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=File\(|Record\(|Records\(|FileCx\(|RecordCx\(|RecordsCx\(|Object\(|Objects\(|ObjectClass\()[\w._-]+</string>
					<key>name</key>
					<string>object.source.m-at</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=LockSystemInfo\()[\w._-]+</string>
					<key>name</key>
					<string>object.source.m-at</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=IndexLookup\(|Index\(|IndexEntry\(|IndexLookupCx\(|IndexLookupResults\(|IndexEntries\()[\w._-]+</string>
					<key>name</key>
					<string>object.source.m-at</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=FullyInMemory\()[\w._-]+</string>
					<key>name</key>
					<string>object.source.m-at</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=NextURN\()[\w._-]+</string>
					<key>name</key>
					<string>object.source.m-at</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=NoDuplicateCheck\()[\w._-]+</string>
					<key>name</key>
					<string>object.source.m-at</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=ToOID\(|ToOIDCx\()[\w._-]+</string>
					<key>name</key>
					<string>object.source.m-at</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=RecordsChanged\(|RecordChanged\(|ObjectChanged\(|RecordCreated\(|RecordsCreated\(|ObjectDirtyFlags\()[\w._-]+</string>
					<key>name</key>
					<string>object.source.m-at</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=RecordTag\()[\w._-]+</string>
					<key>name</key>
					<string>object.source.m-at</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=ObjectSnapshot\(|SnapshotExists\()[\w._-]+</string>
					<key>name</key>
					<string>object.source.m-at</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#control_flow</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[^\n)(]*</string>
					<key>name</key>
					<string>argument.m-at</string>
				</dict>
			</array>
		</dict>
		<key>object_attribute</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>attribute.source.m-at</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>object.source.m-at</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>M-AT Attribute</string>
			<key>match</key>
			<string>^ *(Name|File|Class|Record|Index|Pointer) +([\w.]+) *$</string>
			<key>name</key>
			<string>object.attribute.source.m-at</string>
		</dict>
		<key>object_keyword</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.m-at</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>object.source.m-at</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^ *(:(Object|Record|File|Field|Key|Index|Element|IndexKey)) +([\w.]+) *$</string>
			<key>name</key>
			<string>object.keyword.source.m-at</string>
		</dict>
		<key>other_translator</key>
		<dict>
			<key>begin</key>
			<string>^(#\p{Alpha}+) *$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>translator.source.m-at</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=^#)</string>
			<key>name</key>
			<string>other.translator.source.m-at</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#keyword_line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#attribute_line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#translator_continuation</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<key>screen_translator</key>
		<dict>
			<key>begin</key>
			<string>^(#Screen)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>translator.source.m-at</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=^#)</string>
			<key>name</key>
			<string>screen.translator.source.m-at</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#keyword_line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#object_attribute</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#attribute_line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#translator_continuation</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<key>screencomponent_translator</key>
		<dict>
			<key>begin</key>
			<string>^(#ScreenComponent)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>translator.source.m-at</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=^#)</string>
			<key>name</key>
			<string>screencomponent.translator.source.m-at</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.source.m-at</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>elementset.source.m-at</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^ *(:ElementSet) +([^
()	]+? *$)</string>
					<key>name</key>
					<string>elementset.keyword.source.m-at</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>attribute.source.m-at</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^ *(Name) +[^
()	]+? *$</string>
					<key>name</key>
					<string>other.attribute.source.m-at</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#object_keyword</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keyword_line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#object_attribute</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#attribute_line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#translator_continuation</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<key>screenpage_translator</key>
		<dict>
			<key>begin</key>
			<string>^(#ScreenPage)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>translator.source.m-at</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=^#)</string>
			<key>name</key>
			<string>screenpage.translator.source.m-at</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#keyword_line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#attribute_line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<key>screenrecord_translator</key>
		<dict>
			<key>begin</key>
			<string>^(#ScreenRecord)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>translator.source.m-at</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=^#)</string>
			<key>name</key>
			<string>screenrecord.translator.source.m-at</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#object_keyword</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keyword_line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#attribute_line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#translator_continuation</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<key>string</key>
		<dict>
			<key>comment</key>
			<string>String</string>
			<key>match</key>
			<string>"[^"]*"</string>
			<key>name</key>
			<string>string</string>
		</dict>
		<key>string_list</key>
		<dict>
			<key>comment</key>
			<string>List</string>
			<key>match</key>
			<string>`[^']*'</string>
			<key>name</key>
			<string>string</string>
		</dict>
		<key>translator_continuation</key>
		<dict>
			<key>begin</key>
			<string>^ *(--&gt;)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.m-at</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>other.keyword.source.m-at</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string_list</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#code_region</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.m-at</string>
	<key>uuid</key>
	<string>da222f5a-4cec-4bcd-82ec-93cedfde55b9</string>
</dict>
</plist>
