from .snippets import insert_compound_snippet
from .focus import (
    CACHE_ROOT,
    TRANSLATOR_SEPARATOR,
    TRANSLATOR_LINE_SPLITTER,
    parse_ring_path,
    convert_to_focus_lists,
    get_translated_path,
)
from .settings import (
    get_server_access,
    get_universe_roots,
    get_universes_to_load,
    get_translate_command,
    get_show_doc_setting,
    get_focus_wiki_setting,
    get_fs_wiki_setting,
    get_set_highlighter_setting,
    get_translator_doc_url_overrides_setting,
    get_focus_function_argument_type,
    get_fs_function_doc_url_overrides_setting,
    get_focus_function_doc_url_overrides_setting,
    get_completion_trigger_enabled_setting,
    get_completion_source_enabled_setting,
)
from .sublime import (
    scope_from_view,
    get_member_region,
    split_member_region,

    extract_focus_function,
    extract_fs_function,
    extract_rt_tool,
    extract_operator,
    extract_alias,
    extract_subroutine,
    extract_include_file,
    extract_external_pageset,
    extract_keyword,
    extract_keyword_value,
    extract_attribute,
    extract_attribute_value,
    KEYWORD_ATTRIBUTE_MATCHER,

    split_focus_function,
    strip_alias,
    display_in_output_panel,
    display_in_new_view,
)
from .general import (
    LimitedSizeDict,
    add_to_path,
    create_folder,
    extract_entity,
    get_env,
    merge_paths,
    read_file,
    string_match,
    string_search,
)
from .load_translator_completions import get_translator_completions


__all__ = [
    'CACHE_ROOT',
    'TRANSLATOR_SEPARATOR',
    'TRANSLATOR_LINE_SPLITTER',
    'LimitedSizeDict',
    'add_to_path',
    'create_folder',
    'extract_entity',
    'get_env',
    'get_member_region',
    'insert_compound_snippet',
    'merge_paths',
    'parse_ring_path',
    'read_file',
    'scope_from_view',
    'split_member_region',
    'string_match',
    'string_search',
    'get_translator_completions',
    'convert_to_focus_lists',
    'get_translated_path',

    'extract_focus_function',
    'extract_fs_function',
    'extract_alias',
    'extract_subroutine',
    'extract_include_file',
    'extract_external_pageset',
    'extract_keyword',
    'extract_keyword_value',
    'extract_attribute',
    'extract_attribute_value',

    'split_focus_function',
    'strip_alias',

    'get_server_access',
    'get_universe_roots',
    'get_universes_to_load',
    'get_translate_command',
    'get_show_doc_setting,',
    'get_focus_wiki_setting,',
    'get_fs_wiki_setting,',
    'get_set_highlighter_setting,',
    'get_translator_doc_url_overrides_setting,',
    'get_focus_function_argument_type,',
    'get_focus_function_doc_url_overrides_setting,',
    'get_completion_trigger_enabled_setting',
    'get_completion_source_enabled_setting',
]
