import json
import re

import sublime

FOC_FUNC_COMP = dict()

def plugin_loaded():
    """Assumes the sublime API is loaded.

    Should only be called after the plugin is loaded.

    """
    global FOC_FUNC_COMP
    global SCOPE_MAPPINGS
    FOC_FUNC_COMP = load_foc_func_comp()

def load_foc_func_comp():
    try:
        foc_func_comp = sublime.load_resource(
        'Packages/User/focus function completions.json')
    except IOError:
        foc_func_comp = sublime.load_resource(
            'Packages/Focus/Language/focus function completions.json')
    return json.loads(foc_func_comp)


# TRIGGER_COMMANDS = (('AfterRID',['Record']),
#                     ('AnyRecords',['Record']),
#                     ('CallStructuredCopyLocal',['Object']),
#                     ('CallStructuredCreate',['Object']),
#                     ('CallStructuredExport',['Object']),
#                     ('CallStructuredExportTxn',['Object']),
#                     ('CallStructuredFlush',['Object']),
#                     ('CallStructuredImport',['Object']),
#                     ('CallStructuredImportAdditional',['Object']),
#                     ('CallStructuredPurge',['Object']),
#                     ('CallStructuredSubmit',['Object']),
#                     ('CallSub',['Subroutine']),
#                     ('ClearObjectDirtyFlags',['Object']),
#                     ('CloneObject',['Object']),
#                     ('CloneRecords',['Record']),
#                     ('CloseIndex',['Index']),
#                     ('CloseIndexForIntersect',['Index']),
#                     ('CompareObjectSnapshot',['Object']),
#                     ('CreateObject',['Object']),
#                     ('CreateRecord',['Record']),
#                     ('CreateRecordAsIfImported',['Record']),
#                     ('CreateRecordNoDuplicateCheck',['Record']),
#                     ('CreateRIDList',['Record']),
#                     ('DeleteIndexEntries',['Index']),
#                     ('DeleteIndexEntriesCx',['Index']),
#                     ('DeleteRecords',['Record']),
#                     ('ExportObject',['Object']),
#                     ('ExportObjectCx',['Object']),
#                     ('Field',['Field']),
#                     ('FindRID',['Record']),
#                     ('FirstRID',['Record']),
#                     ('FileFullyInMemory',['File']),
#                     ('FlushObject',['Object']),
#                     ('FlushObjectClass',['Object']),
#                     ('FlushObjects',['Object']),
#                     ('FlushObjectSnapshot',['Object']),
#                     ('FlushRecords',['Record']),
#                     ('FlushRIDList',['Record']),
#                     ('FormIndexRecords',['Index']),
#                     ('GetCurrentOID',['Object']),
#                     ('GetCurrentRID',['Record']),
#                     ('GetCurrentRIDList',['Record']),
#                     ('GetElementLabel',['Field', 'Key']),
#                     ('GetField',['Field']),
#                     ('GetFieldExternal',['Field']),
#                     ('GetKey',['Key']),
#                     ('GetKeyExternal',['Key']),
#                     ('GetLastTimeStampForFile',['File']),
#                     ('GetLastTimeStampForObject',['Object']),
#                     ('GetLastTimeStampForObjects',['Object']),
#                     ('GetLocal',['Local']),
#                     ('GetObjectLongLockParmas',['LongLock']),
#                     ('GetObjectLongLockSystemInfo',['LongLock']),
#                     ('GetObjectLongLockValue',['LongLock']),
#                     ('GetRecord',['Record']),
#                     ('GetRecordAsOf',['Record']),
#                     ('GetRecordEffectiveOn',['Record']),
#                     ('GetStateVariable',['State']),
#                     ('GetSystemVariable',['System']),
#                     ('ImportFile',['File']),
#                     ('ImportFileBatchesToStackWhile',['Subroutine']),
#                     ('ImportFileBatchesWhile',['File']),
#                     ('ImportFileCx',['File']),
#                     ('ImportFileHxAsOf',['File']),
#                     ('ImportFileToOID',['File']),
#                     ('ImportFileToOIDCx',['File']),
#                     ('ImportRecord',['Record']),
#                     ('ImportRecordCx',['Record']),
#                     ('ImportRecordEffectiveOn',['Record']),
#                     ('ImportRecordEffectiveOnCx',['Record']),
#                     ('ImportRecordHxAsOf',['Record']),
#                     ('ImportRecords',['Record']),
#                     ('ImportRecordsConditional',['Record']),
#                     ('ImportRecordsConditionalCx',['Record']),
#                     ('ImportRecordsCx',['Record']),
#                     ('ImportRecordsHxAsOf',['Record']),
#                     ('ImportRecordsSince',['Record']),
#                     ('ImportRecordsToOID',['Record']),
#                     ('ImportRecordsToOIDCx',['Record']),
#                     ('ImportRecordToOID',['Record']),
#                     ('ImportRecordToOIDCx',['Record']),
#                     ('IndexKey',['IndexKey']),
#                     ('IndexKeyExternal',['IndexKey']),
#                     ('IndexLookup',['Index']),
#                     ('IndexLookupIntoArray',['Index']),
#                     ('InsertIndexEntries',['Index']),
#                     ('InsertIndexEntriesCx',['Index']),
#                     ('Key',['Key']),
#                     ('LastRID',['Record']),
#                     ('LastServerKey',['Key']),
#                     ('ListChangedRecords',['Object']),
#                     ('ListMemberNumber',['Subroutine']),
#                     ('ListOIDs',['Object']),
#                     ('ListRIDs',['Record']),
#                     ('LockObjectLong',['LongLock']),
#                     ('LockObjectShort',['LongLock']),
#                     ('LockObjectShortCx',['LongLock']),
#                     ('MaxClientKey',['Key']),
#                     ('MoreIndexEntries',['Index']),
#                     ('MoreRID',['Record']),
#                     ('MoveRecordAfter',['Record']),
#                     ('MoveRecordBefore',['Record']),
#                     ('NextIndexEntry',['Index']),
#                     ('NextIntersectOID',['Object']),
#                     ('NextRID',['Record']),
#                     ('NextURN',['Key']),
#                     ('ObjectChanged',['Object']),
#                     ('ObjectLongLockStillOwned',['LongLock']),
#                     ('ObjectSnapshotExists',['Object']),
#                     ('ObjectUpdatedSinceImport',['Object']),
#                     ('OpenForRecordsSince',['Record']),
#                     ('OpenIndex',['Index']),
#                     ('OpenIndexForIntersect',['Index']),
#                     ('PurgeObject',['Object']),
#                     ('PurgeObjectCx',['Object']),
#                     ('PutField',['Field']),
#                     ('PutLocal',['Local']),
#                     ('PutRecord',['Record']),
#                     ('PutStateVariable',['State']),
#                     ('PutSystemVariable',['System']),
#                     ('ReadRID',['Record']),
#                     ('RecordChanged',['Record']),
#                     ('RecordCreated',['Record']),
#                     ('RecordsChanged',['Record']),
#                     ('RecordsFullyInMemory',['Record']),
#                     ('RecordTag',['Record']),
#                     ('ReleaseForeignObjectLongLock',['LongLock']),
#                     ('RestoreObjectSnapshot',['Object']),
#                     ('RetrieveField',['Field']),
#                     ('RetrieveFieldExternal',['Field']),
#                     ('RetrieveRecord',['Record']),
#                     ('RetrieveRecordCx',['Record']),
#                     ('RollUpFile',['File']),
#                     ('SaveObjectSnapshot',['Object']),
#                     ('SetCurrentOID',['Object']),
#                     ('SetCurrentRID',['Record']),
#                     ('SetCurrentRIDList',['Record']),
#                     ('SortRecords',['Record']),
#                     ('UnlockObjectLong',['LongLock']),
#                     ('UnlockObjectShort',['LongLock']),
#                     ('UnlockObjectShortCx',['LongLock']),
#                     ('UpdateIndexEntries',['Index']),
#                     ('UpdateIndexEntriesCx',['Index']),
#                     ('UpdateObjectLongLock',['LongLock']))

TRANSLATOR_COMPLETIONS = {'#Alias':           {':Alias':  {'Value': '',
                                                           'Scope': ['Global','Local']}},
                          '#BodyButtons':     {':BodyButtons': {'VSpacing': '',
                                                                'OnAfterInit': '',
                                                                ':Row': {'Arrange': ['"Horizontal"', '"Matrix"', '"Vertical"'],
                                                                         'HSpacing': '',
                                                                         'Label': '',
                                                                         'Matrix': '',
                                                                         'Separator': '',
                                                                         'ShowCondition': '',
                                                                         'VSeparator': '',
                                                                         'VSpacing': '',
                                                                         ':Button': {'Condition': '',
                                                                                     'DownColor': ['"Blue"', '"Green"', '"Red"'],
                                                                                     'Group': '',
                                                                                     'Function': ['Action', 'Select', 'Page'],
                                                                                     'Label': '',
                                                                                     'Logic': '',
                                                                                     'Name': '',
                                                                                     'Page': '',
                                                                                     'PageLogic': '',
                                                                                     'ShowCondition': '',
                                                                                     'StartDownCondition': '',
                                                                                     'Style': ['"Button"', '"Hyperlink"', '"Radio"', 
                                                                                               '"RightArrow"', '"LeftArrow"', '"Manual"'],
                                                                                     'UnSelect': '',
                                                                                     'UpColor': ['"Blue"', '"Green"', '"Red"']
                                                                                    }
                                                                        }
                                                               }
                                              },
                          '#DataDef':         {':Object': {'AuditReadCondition': '',
                                                           'AuditWriteCondition': '',
                                                           'BucketFiles': '',
                                                           'CodeBase': '',
                                                           'CustomData': ['Yes','No'],
                                                           'GoverningMutex': 'Mutex',
                                                           'OIDCopiedFrom': 'Object',
                                                           'OIDOrigin': ['System','User','CopiedFrom','TempOnly','Calculated'],
                                                           'OnExport': '',
                                                           'PurgeAllowed': ['Yes','No'],
                                                           'RootRT': '',
                                                           'RootTT': '',
                                                           'SuppressTxnMutex': ['Yes','No'],
                                                           ':File':   {'CacheLocally': ['Yes','No'],
                                                                       'FileFormat': ['mtSo','mtTo'],
                                                                       'Folder': '',
                                                                       'MainFile': ['Yes','No'],
                                                                       'ServerCurrentRecordFilteringExempt': ['Yes','No'],
                                                                       ':Record': {'CustomExtendable': ['Yes','No'],
                                                                                   'ExtensionOf': 'Record', 
                                                                                   'GoverningMutex': 'Mutex',
                                                                                   'GoverningMutexExempt': ['Yes','No'],
                                                                                   'MutexLevel': ['OID','RID'],
                                                                                   'Parent': 'Record',   
                                                                                   'PreserveOrder': ['Yes','No'],
                                                                                   'Tag': '',
                                                                                   ':Embedded': {'Offset': ''
                                                                                                },
                                                                                   ':Field': {'Choices': '',      
                                                                                              'ChoiceMap': '',    
                                                                                              'Compute': '',      
                                                                                              'DataType': ['AGE','ATTACHMENT','BDATE',
                                                                                                           'BP','Choice','DATE','DATETIME',
                                                                                                           'DATETIME.OT','DATETIME5','DAY',
                                                                                                           'DEC','DURATION','DURATION5',
                                                                                                           'EDATE','EMAIL','ExternalFilePointer',
                                                                                                           'FILENAME','FILENAME.MC','FREE',
                                                                                                           'HHMM','HHMM5','HHMMU','INT',
                                                                                                           'IPADDRESS','IPPORT','LENGTH','LIST',
                                                                                                           'LOGICSTRING','MONEY','MONTH',
                                                                                                           'MText','NAMEPART','NUMERIC',
                                                                                                           'ObjectID','PDEC','PFXINT','PHONE',
                                                                                                           'PINT','PMONEY','PlainText',
                                                                                                           'RELATIONSHIPSTRING','SDEC','SINT',
                                                                                                           'SMONEY','TEMPERATURE','TIMEZONE',
                                                                                                           'UNTYPED','URN','VOLUME','WEIGHT',
                                                                                                           'YEAR','YN','YNCOMMENT','ZIP.POST'],
                                                                                              'ExternalFile': '',
                                                                                              'ExternalOID': ['Fixed','Editable'],
                                                                                              'Label': '',    
                                                                                              'Length': '',       
                                                                                              'Offset': '',
                                                                                              'Pointer': 'Object',
                                                                                              'Precision': ''},
                                                                                   ':Key': {'Choices': '',      
                                                                                            'ChoiceMap': '',
                                                                                            'Context': '',     
                                                                                            'DataType': ['AGE','ATTACHMENT','BDATE',
                                                                                                         'BP','Choice','DATE','DATETIME',
                                                                                                         'DATETIME.OT','DATETIME5','DAY',
                                                                                                         'DEC','DURATION','DURATION5',
                                                                                                         'EDATE','EMAIL','ExternalFilePointer',
                                                                                                         'FILENAME','FILENAME.MC','FREE',
                                                                                                         'HHMM','HHMM5','HHMMU','INT',
                                                                                                         'IPADDRESS','IPPORT','LENGTH','LIST',
                                                                                                         'LOGICSTRING','MONEY','MONTH',
                                                                                                         'MText','NAMEPART','NUMERIC',
                                                                                                         'ObjectID','PDEC','PFXINT','PHONE',
                                                                                                         'PINT','PMONEY','PlainText',
                                                                                                         'RELATIONSHIPSTRING','SDEC','SINT',
                                                                                                         'SMONEY','TEMPERATURE','TIMEZONE',
                                                                                                         'UNTYPED','URN','VOLUME','WEIGHT',
                                                                                                         'YEAR','YN','YNCOMMENT','ZIP.POST'],
                                                                                            'Label': '',    
                                                                                            'Length': '',
                                                                                            'Pointer': 'Object'}
                                                                                  }
                                                                     },
                                                          ':Temp':   {'Scope': ['Process','Global'],
                                                                      ':Record': {'CustomExtendable': ['Yes','No'],
                                                                                  'ExtensionOf': 'Record', 
                                                                                  'GoverningMutex': 'Mutex',
                                                                                  'GoverningMutexExempt': ['Yes','No'],
                                                                                  'MutexLevel': ['OID','RID'],
                                                                                  'Parent': 'Record',   
                                                                                  'PreserveOrder': ['Yes','No'],
                                                                                  'Tag': '',
                                                                                  ':Embedded': {'Offset': ''},
                                                                                  ':Field': {'Choices': '',      
                                                                                             'ChoiceMap': '',    
                                                                                             'Compute': '',      
                                                                                             'DataType': ['AGE','ATTACHMENT','BDATE',
                                                                                                          'BP','Choice','DATE','DATETIME',
                                                                                                          'DATETIME.OT','DATETIME5','DAY',
                                                                                                          'DEC','DURATION','DURATION5',
                                                                                                          'EDATE','EMAIL','ExternalFilePointer',
                                                                                                          'FILENAME','FILENAME.MC','FREE',
                                                                                                          'HHMM','HHMM5','HHMMU','INT',
                                                                                                          'IPADDRESS','IPPORT','LENGTH','LIST',
                                                                                                          'LOGICSTRING','MONEY','MONTH',
                                                                                                          'MText','NAMEPART','NUMERIC',
                                                                                                          'ObjectID','PDEC','PFXINT','PHONE',
                                                                                                          'PINT','PMONEY','PlainText',
                                                                                                          'RELATIONSHIPSTRING','SDEC','SINT',
                                                                                                          'SMONEY','TEMPERATURE','TIMEZONE',
                                                                                                          'UNTYPED','URN','VOLUME','WEIGHT',
                                                                                                          'YEAR','YN','YNCOMMENT','ZIP.POST'],
                                                                                             'ExternalFile': '',
                                                                                             'ExternalOID': ['Fixed','Editable'],
                                                                                             'Label': '',    
                                                                                             'Length': '',       
                                                                                             'Offset': '',
                                                                                             'Pointer': 'Object',
                                                                                             'Precision': ''},
                                                                                  ':Key': {'Choices': '',      
                                                                                           'ChoiceMap': '',
                                                                                           'Context': '',     
                                                                                           'DataType': ['AGE','ATTACHMENT','BDATE',
                                                                                                        'BP','Choice','DATE','DATETIME',
                                                                                                        'DATETIME.OT','DATETIME5','DAY',
                                                                                                        'DEC','DURATION','DURATION5',
                                                                                                        'EDATE','EMAIL','ExternalFilePointer',
                                                                                                        'FILENAME','FILENAME.MC','FREE',
                                                                                                        'HHMM','HHMM5','HHMMU','INT',
                                                                                                        'IPADDRESS','IPPORT','LENGTH','LIST',
                                                                                                        'LOGICSTRING','MONEY','MONTH',
                                                                                                        'MText','NAMEPART','NUMERIC',
                                                                                                        'ObjectID','PDEC','PFXINT','PHONE',
                                                                                                        'PINT','PMONEY','PlainText',
                                                                                                        'RELATIONSHIPSTRING','SDEC','SINT',
                                                                                                        'SMONEY','TEMPERATURE','TIMEZONE',
                                                                                                        'UNTYPED','URN','VOLUME','WEIGHT',
                                                                                                        'YEAR','YN','YNCOMMENT','ZIP.POST'],
                                                                                           'Label': '',    
                                                                                           'Length': '',
                                                                                           'Pointer': 'Object'}
                                                                                 }
                                                                     } 
                                                         }
                                              },  
                          '#ImportExport':    {':Object': {'AfterImportCondition': '',
                                                           'Class': 'Object',
                                                           'DisableExport': '',
                                                           'OnAfterCommit': '',
                                                           'OnAfterImport': '',
                                                           'OnBeforeExport': '',
                                                           ':CopyLocal': {'Index': 'Index',
                                                                          'IndexAll': ['Yes', 'No']
                                                                         },
                                                           ':Export': {'Index': 'Index',
                                                                       'Condition': '',
                                                                       'ConditionFailureMessage': '',
                                                                       'IndexAll': ['Yes', 'No']
                                                                      },
                                                           ':Import': {'Condition': '',
                                                                       'File': 'File',
                                                                       ':Record': {'Name': 'Record',
                                                                                   'RID': ''
                                                                                  },
                                                                       ':Records': {'Name': 'Record',
                                                                                    'RID': ''}
                                                                                   },
                                                           ':ImportAdditional': {'Condition': '',
                                                                                 'File': 'File',
                                                                                 ':Record': {'Name': 'Record',
                                                                                             'RID': ''
                                                                                            },
                                                                                 ':Records': {'Name': 'Record',
                                                                                              'RID': ''
                                                                                             }
                                                                                },
                                                           ':LongLock': {'Name': 'LongLock'},
                                                           ':Purge': {'Index': 'Index',
                                                                      'IndexAll': ['Yes', 'No']}
                                                           }
                                              },
                          '#Include':         {':Source': {'File': 'Include',
                                                           'Folder': '',
                                                           'Local': ['Yes', 'No'],
                                                           'RootRT': '',
                                                           'RootTT': ''
                                                          }
                                              },
                          '#Locals':          {':Name': 'Local'},
                          '#Preamble':        {':Options': {'AskCredentials': ['Yes', 'No'],
                                                            'BkgSessionID': '',
                                                            'NullProcessGroup': ['Yes', 'No'],
                                                            'RestoreDataOnExit': '',
                                                            'ShareData': '',
                                                            'StackCxQueue': ['Yes', 'No'],
                                                            'SymbolSet': ['English', 'Arabic'],
                                                            'SystemTrayIcon': '',
                                                            'SystemTrayText': '',
                                                            'Type': ['Program',
                                                                     'Process',
                                                                     'Tool',
                                                                     'Iconset',
                                                                     'ServiceStartProgram',
                                                                     'Startup',
                                                                     'WebRoutine',
                                                                     'WebStartProgram',
                                                                     'LinkedPlatformStartProgram'],
                                                            'UniqueJobID': ""
                                                           },
                                               ':WebPopUp': {'Size': ['Petite', 
                                                                      'Small', 
                                                                      'Medium', 
                                                                      'Large', 
                                                                      'ExtraLarge']
                                                            },
                                               ':Window': {'Exact': ['Height', 'Width'],
                                                           'HideOtherWindows': ['Yes', 'No'],
                                                           'InitialFont': ['Petite',
                                                                           'Small',
                                                                           'SmallBold',
                                                                           'SmallBoldUnderscore',
                                                                           'SmallUnderscore',
                                                                           'Medium',
                                                                           'MediumBold'],
                                                           'InitialState': ['Normalized', 'Minimized', 'Maximized'],
                                                           'Position': ['Body', 'Window', 'Display', 'Header', 'Footer'],
                                                           'Size': ['Petite', 
                                                                    'Small', 
                                                                    'Medium', 
                                                                    'Large', 
                                                                    'ExtraLarge',
                                                                    'Exact',
                                                                    'Auto'],
                                                           'Timeout': ['Short', 'Medium', 'Long', 'Immediate', 'None'],
                                                           'Title': ''
                                                          }
                                              },
                          '#ScreenRecord':    {':Options': {'AllowCustomData': ['Yes', 'No']
                                                           },
                                               ':Record': {':Record': 'Record',
                                                           'DeleteCondition': '',
                                                           'EditCondition': '',
                                                           'ExitCondition': '',    
                                                           'IncludeCondition': '', 
                                                           'InitialCurrentRID': ['First', 'Last', 'Keep', 'None'],
                                                           'NewCondition': '',
                                                           'OnAfterDelete': '',
                                                           'OnAfterInitialSort': '',
                                                           'OnBeforeCreate': '',
                                                           'OnBeforeOrderChange': '',
                                                           'OnCreate': '',
                                                           'OnDelete': '',
                                                           'OnDeleteCondition': '',
                                                           'OnExit': '',
                                                           'OnInstanceChange': '',
                                                           'OnOrderChange': '',
                                                           'Sibling': 'Record',
                                                           'SortBy': '',
                                                           'SortOrder': ['Ascending', 'Descending']
                                                          }
                                              },
                          '#Screen':          {':Object': {'CancelCondition': '',
                                                           'Class': 'Object',
                                                           'EditOnlyRecords': '',
                                                           'ExternalOIDSeed': '',
                                                           'Identifier': '',
                                                           'NonEditableElements': '',
                                                           'NonEditableRecords': '',
                                                           'OnBeforeCancel': '',
                                                           'OnCancel': '',
                                                           'OnCreate': '',
                                                           'Repeat': ['Yes', 'No']},
                                               ':Session': {'EditorLinkAction': '',
                                                            'ForceFooterInit': ['Yes', 'No'],
                                                            'ForceTriggerWindow': ['Yes', 'No'],
                                                            'OnAfterInit': '',
                                                            'OnEntry': '',
                                                            'OnExit': '',
                                                            'OnInitialPage': '',
                                                            'OnProcessMessage': '',
                                                            'ShowLookupIcon': ''}
                                                           },
                          '#ScreenComponent': {':Display': {':Blank': '',
                                                            ':Cell': '',
                                                            'Anchor': '',
                                                            'Arrange': ['Horizontal', 
                                                                        'Vertical', 
                                                                        'MatrixVertical', 
                                                                        'MatrixHorizontal', 
                                                                        'MatrixTable'],
                                                            'CellLabelStyle': '',
                                                            'CellLabelWidth': ['5%', '10%', '15%', '20%', '25%', '30%', '35%','40%', '50%', '60%', '70%', '90%'],
                                                            'CellValueStyle': '',
                                                            'ColLabel': '',
                                                            'ColLabelHover': '',
                                                            'ColLabelStyle': '',
                                                            'ColLabelWidth': ['5%', '10%', '15%', '20%', '25%', '30%', '35%','40%', '50%', '60%', '70%', '90%'],
                                                            'ColValue': '',
                                                            'ComponentLabel': '',
                                                            'ComponentLabelStyle': '',
                                                            'ComponentLabelType': ['Floating', 'Attached'],
                                                            'DividerOverride': '',
                                                            'EvaluationMethod': ['ByColumn', 'ByRow'],
                                                            'ExitCondition': '',
                                                            'GrayBarReset': '',
                                                            'GrayBarStartColor': '',
                                                            'GrayBars': ['Yes', 'No'],
                                                            'GrayBarsOnRowLabel': ['Yes', 'No'],
                                                            'KeyNavigable': '',
                                                            'ObjectClass': 'Object',
                                                            'OnAfterClick': '',
                                                            'OnClick': '',
                                                            'OnClickDown': '',
                                                            'OnClickUp': '',
                                                            'OnEntry': '',
                                                            'OnExit': '',
                                                            'OnKeyStroke': '',
                                                            'OnNavClick': '',
                                                            'OnRightClickDown': '',
                                                            'OnRightClickUp': '',
                                                            'OnScrollClick': '',
                                                            'PivotLabel': '',
                                                            'PivotLabelHover': '',
                                                            'PivotLabelStyle': '',
                                                            'PivotLabelWidth': ['5%', '10%', '15%', '20%', '25%', '30%', '35%','40%', '50%', '60%', '70%', '90%'],
                                                            'RowLabel': '',
                                                            'RowLabelHover': '',
                                                            'RowLabelStyle': '',
                                                            'RowLabelWidth': ['5%', '10%', '15%', '20%', '25%', '30%', '35%','40%', '50%', '60%', '70%', '90%'],
                                                            'RowValue': '',
                                                            'Style': ''
                                                          }, 
                                               ':ElementSet': {':Element': {':Element': 'Field Key',
                                                                             'AllowNilPseudoKey': ['Yes', 'No'],
                                                                             'AssistedEntry': '',
                                                                             'AutoGen': '',
                                                                             'CDDataType': '',
                                                                             'CDDateTime': '',
                                                                             'CDOtherInfo': '',
                                                                             'CDQuery': '',
                                                                             'CDUser': '',
                                                                             'ChangeCondition': '',
                                                                             'CheckAll': ['Yes', 'No'],
                                                                             'Choices': '',
                                                                             'Columns': '',
                                                                             'DataTypeCheck': ['Yes', 'No'],
                                                                             'DisableToggle': ['Yes', 'No'],
                                                                             'EditCondition': '',
                                                                             'HiddenDataEntry': ['Yes', 'No'],
                                                                             'InputMethod': ['DropDown', 'RadioButton', 'Checkbox'],
                                                                             'Label': '',
                                                                             'LabelHover': '',
                                                                             'LabelAlign': ['Left', 'Right', 'Center'],
                                                                             'LabelPosition': ['Top', 'Left'],
                                                                             'LookupCondition': '',
                                                                             'MultiSelectLookup': ['Yes', 'No'],
                                                                             'OnAfterChange': '',
                                                                             'OnAfterChangeRendered': '',
                                                                             'OnChange': '',
                                                                             'OnCheckBoxClick': '',
                                                                             'OnKeyPress': '',
                                                                             'OnLookup': '',
                                                                             'OverrideDisplay': '',
                                                                             'PlainTextHeight': ['Petite', 'Small', 'Medium', 'Large', 'ExtraLarge'],
                                                                             'PointerDisplay': ['Yes', 'No'],
                                                                             'RadioButtonHeader': ['Yes', 'No'],
                                                                             'RecordLookup': '',
                                                                             'RecordLookupRID': '',
                                                                             'Repeat': ['Yes', 'No'],
                                                                             'Required': '',
                                                                             'RequiredOn': '',
                                                                             'ShowAssistedEntry': '',
                                                                             'ShowCondition': '',
                                                                             'Width': ['5%', '10%', '15%', '20%', '25%', '30%', '35%','40%', '50%', '60%', '70%', '90%']
                                                                          },
                                                               ':ViewedValue': {':ViewedValue': 'Field'
                                                                               },
                                                               ':Blank': '',
                                                               'Action': '',   
                                                               'ActionIcon': '',   
                                                               'ActionIconHover': '',   
                                                               'Arrange': ['Vertical', 'Horizontal', 'MatrixVertical', 'MatrixHorizontal', 'Checkbox'],
                                                               'CDQuery': '',   
                                                               'ComponentLabel': '',   
                                                               'ComponentLabelStyle': '',   
                                                               'ComponentLabelType': ['Floating', 'Attached'],
                                                               'Control': {'Object', 'Seed'},
                                                               'ControlMultiple': ['Yes', 'No'],  
                                                               'DeleteCondition': '',   
                                                               'ExitCondition': '',
                                                               'InstanceLabel': '',
                                                               'InstanceLabelHover': '',   
                                                               'LabelAlign': ['Left', 'Center', 'Right'],
                                                               'NewCondition': '',   
                                                               'NullNavBar': '',   
                                                               'OnAfterDeleteCustomRecord': '',
                                                               'OnDeleteCustomRecord': '',   
                                                               'OnEntry': '',   
                                                               'OnExit': '',   
                                                               'OnKeyStroke': '',   
                                                               'Record': 'Record',
                                                               'Required': '',   
                                                               'RequiredFieldIndicator': ['System', 'User'],
                                                               'RequiredOn': '',
                                                               'Rows': '',
                                                               'ShowDeleteRecordIcon': '',   
                                                               'ShowInsertRecordIcon': '',   
                                                               'ShowMoveRecordDownIcon': '',   
                                                               'ShowMoveRecordUpIcon': '',   
                                                               'ShowNewRecordIcon': '',
                                                               'SuppressRecordIcons': '',   
                                                               'UsePointer': '',
                                                               'Width': ['5%', '10%', '15%', '20%', '25%', '30%', '35%','40%', '50%', '60%', '70%', '90%'],
                                                               'WidthGroup': ''
                                                             },
                                               ':Index': {':Column': {'Align': '', 
                                                                      'Anchor': '',  
                                                                      'DividerOverride': '', 
                                                                      'Label': '', 
                                                                      'LabelAlign': '',  
                                                                      'LabelHover': '',  
                                                                      'LabelStyle': '',  
                                                                      'LeftIcon': '',  
                                                                      'LeftIconAction': '',  
                                                                      'LeftIconHover': '', 
                                                                      'Name': '',
                                                                      'RightIcon': '', 
                                                                      'RightIconAction': '', 
                                                                      'RightIconHover': '',  
                                                                      'ShowCondition': '', 
                                                                      'SortValue': '', 
                                                                      'Sortable': '',  
                                                                      'Value': '', 
                                                                      'ValueStyle': '',  
                                                                      'Width': ['5%', '10%', '15%', '20%', '25%', '30%', '35%','40%', '50%', '60%', '70%', '90%']
                                                                     },
                                                          'CDQuery': '', 
                                                          'ComponentLabel': '',  
                                                          'ComponentLabelClick': '', 
                                                          'ComponentLabelStyle': '', 
                                                          'ComponentLabelType': ['Floating', 'Attached'],
                                                          'ControlMultiple': ['Yes','No'], 
                                                          'DeleteCondition': '', 
                                                          'DividerOverride': '', 
                                                          'ElementSet': '',
                                                          'ExitCondition': '', 
                                                          'GrayBarReset': '',  
                                                          'GrayBarStartColor': '', 
                                                          'GrayBars': ['Yes','No'],    
                                                          'HighLightBar': '',  
                                                          'LeftNavBar': ['Yes','No'],  
                                                          'NewCondition': '',  
                                                          'NullNavBar': '',  
                                                          'OnAfterSelect': '', 
                                                          'OnAfterUserSort': '', 
                                                          'OnDownArrowKey': '',  
                                                          'OnEntry': '', 
                                                          'OnExit': '',  
                                                          'OnKeyStroke': '', 
                                                          'OnPageDownKey': '', 
                                                          'OnPageUpKey': '', 
                                                          'OnReturnKey': '', 
                                                          'OnRightClickDown': '',  
                                                          'OnRightClickUp': '',  
                                                          'OnSelect': '',  
                                                          'OnUpArrowKey': '',  
                                                          'Record': 'Record', 
                                                          'Rows': '',  
                                                          'ShowDeleteRecordIcon': '',  
                                                          'ShowInsertRecordIcon': '',  
                                                          'ShowMoveRecordDownIcon': '',  
                                                          'ShowMoveRecordUpIcon': '',  
                                                          'ShowNewRecordIcon': '', 
                                                          'Style': '', 
                                                          'SuppressRecordIcons': ''
                                                         },
                                               ':Search': '',
                                               ':SubBodyButtonSet': {':Button': ''
                                                                    }
                                              }, 
                          '#ScreenPage': {':ContainerPage': {'OnEntry': '',
                                                             ':Container': {':Container': ['TaskPage',
                                                                                           'TaskBlock',
                                                                                           'VDepend',
                                                                                           'BoxDepend',
                                                                                           'BoxDependDropDown',
                                                                                           'TabBlock',
                                                                                           'InlineMessage',
                                                                                           'VBlock',
                                                                                           'HBlock',
                                                                                           'MBlock',
                                                                                           'YBlock',
                                                                                           'XBlock'],
                                                                            'Arrange': ['Horizontal','Vertical'],
                                                                            'Label': '',
                                                                            'Hmargin': '',
                                                                            'Vmargin': '',
                                                                            'ItemSpacing': '',
                                                                            'Style': '',
                                                                            'Align': ['Left','Right','Center'],
                                                                            'VAlign': ['Top','Bottom','Center'],
                                                                            'IndentSpace': '',
                                                                            'IndentLevel': '',
                                                                            'IndentArrow': '',
                                                                            'Icon': '',
                                                                            'MinHeight': '',
                                                                            'MinWidth': '',
                                                                            ':Region': 'ScreenRegion',
                                                                            ':Component': {'Align': ['Left','Center','Right'],
                                                                                           'Display': 'Display',
                                                                                           'DisplayPosition': '',
                                                                                           'ElementSet': 'ElementSet',
                                                                                           'IndentLevel': '',
                                                                                           'Index': 'ScreenIndex',
                                                                                           'Label': '',
                                                                                           'LabelStyle': '',
                                                                                           'LabelType': ['Floating','Attached'],
                                                                                           'Search': 'ScreenSearch',
                                                                                           'ShowCondition': '',
                                                                                           'SubBodyButtonSet': '',
                                                                                           'SuppressBlank': ['Yes','No']
                                                                                          }
                                                                           }
                                                            },
                                          ':ContainerRegion': {':Container': {':Container': ['TaskPage',
                                                                                             'TaskBlock',
                                                                                             'VDepend',
                                                                                             'BoxDepend',
                                                                                             'BoxDependDropDown',
                                                                                             'TabBlock',
                                                                                             'InlineMessage',
                                                                                             'VBlock',
                                                                                             'HBlock',
                                                                                             'MBlock',
                                                                                             'YBlock',
                                                                                             'XBlock'],
                                                                              'Arrange': ['Horizontal','Vertical'],
                                                                              'Label': '',
                                                                              'Hmargin': '',
                                                                              'Vmargin': '',
                                                                              'ItemSpacing': '',
                                                                              'Style': '',
                                                                              'Align': ['Left','Right','Center'],
                                                                              'VAlign': ['Top','Bottom','Center'],
                                                                              'IndentSpace': '',
                                                                              'IndentLevel': '',
                                                                              'IndentArrow': '',
                                                                              'Icon': '',
                                                                              'MinHeight': '',
                                                                              'MinWidth': '',
                                                                              ':Region': 'ScreenRegion',
                                                                              ':Component': {'Align': ['Left','Center','Right'],
                                                                                             'Display': 'Display',
                                                                                             'DisplayPosition': '',
                                                                                             'ElementSet': 'ElementSet',
                                                                                             'IndentLevel': '',
                                                                                             'Index': 'ScreenIndex',
                                                                                             'Label': '',
                                                                                             'LabelStyle': '',
                                                                                             'LabelType': ['Floating','Attached'],
                                                                                             'Search': 'ScreenSearch',
                                                                                             'ShowCondition': '',
                                                                                             'SubBodyButtonSet': '',
                                                                                             'SuppressBlank': ['Yes','No']
                                                                                            }
                                                                             }
                                                              }, 
                                         ':ExternalPageSet': {'Codebase': '',
                                                              'Source': '',
                                                              'PageName': ''
                                                             }
                                         },
                          '#ScreenStyle': {':Style': {'Align': ['Left', 'Right', 'Center'],
                                                      'BgColor': ['Aquamarine', 'Block', 'Blue', 'Button', 'Cyan', 'Dark', 'Green', 'Header', 'HighLight', 'Light', 'LowLight', 'Magenta', 'Orange', 'PageBorder', 'Red', 'Sapphire', 'Separator', 'ShadedBlue', 'ShadedCyan', 'ShadedDark', 'ShadedGreen', 'ShadedLight', 'ShadedMagenta', 'ShadedRed', 'ShadedSystemDarkToMedium', 'ShadedSystemLightToMedium', 'ShadedSystemLightToVeryLight', 'ShadedSystemMediumToDark', 'ShadedSystemMediumToLight', 'ShadedSystemVeryLightToDark', 'ShadedSystemVeryLightToLight', 'ShadedYellow', 'System', 'SystemLight', 'SystemMedium', 'TableLabel', 'Tan', 'Transparent', 'Violet', 'Wallpaper', 'Wheat', 'White', 'WhiteBar', 'Yellow'],
                                                      'Divider': ['Transparent', 'Dark', 'Black', 'Clear', 'Light', 'White', 'Table'],
                                                      'DividerDirection': ['Horizontal', 'Vertical'],
                                                      'Edge': ['Clear', 'Black', 'Dark', 'Frame', 'Inner', 'Light', 'None', 'Outer', 'Perimeter', 'Raised', 'Sunken', 'Transparent', 'White', 'Button', 'PageBorder', 'Block', 'BlockExpanded', 'Table', 'InputBox'],
                                                      'FgColor': ['Aquamarine', 'Block', 'Blue', 'Button', 'Cyan', 'Dark', 'Green', 'Header', 'HighLight', 'Light', 'LowLight', 'Magenta', 'Orange', 'PageBorder', 'Red', 'Sapphire', 'Separator', 'ShadedBlue', 'ShadedCyan', 'ShadedDark', 'ShadedGreen', 'ShadedLight', 'ShadedMagenta', 'ShadedRed', 'ShadedSystemDarkToMedium', 'ShadedSystemLightToMedium', 'ShadedSystemLightToVeryLight', 'ShadedSystemMediumToDark', 'ShadedSystemMediumToLight', 'ShadedSystemVeryLightToDark', 'ShadedSystemVeryLightToLight', 'ShadedYellow', 'System', 'SystemLight', 'SystemMedium', 'TableLabel', 'Tan', 'Transparent', 'Violet', 'Wallpaper', 'Wheat', 'White', 'WhiteBar', 'Yellow'],
                                                      'Font': ['Petite', 'Small', 'SmallBold', 'SmallBoldUnderscore', 'SmallUnderscore', 'Medium', 'MediumBold', 'SmallFixed', 'SmallArabic', 'MediumArabic'],
                                                      'HoverCursor': ['Yes', 'No'],
                                                      'Show': ['Yes', 'No']
                                                     }
                                          },
                          '#Translation': {':Options': {'Result': ['Run', 'FSFile', 'MSFile', 'Time', 'DisplayLog', 'Log']
                                                       },
                                           ':Product': {'CodeBase': '',
                                                        'Type': ['CD-RowSet', 
                                                                 'ChildScreen', 
                                                                 'ConversionSet', 
                                                                 'DataDef', 
                                                                 'DataType', 
                                                                 'ExternalFrameSet', 
                                                                 'ExternalPageSet', 
                                                                 'ExternalSubroutineSet', 
                                                                 'ExternalWebRegionSet', 
                                                                 'HelpSet', 
                                                                 'Iconset', 
                                                                 'Lookup', 
                                                                 'Report', 
                                                                 'Screen', 
                                                                 'ScreenStyle', 
                                                                 'Service', 
                                                                 'StackedScreen', 
                                                                 'Toolset', 
                                                                 'Unstructured', 
                                                                 'WebRoutine', 
                                                                 'WebRoutineHH', 
                                                                 'WebStyle', 
                                                                 'WebValidation']
                                                       },
                                           ':Source': {'File': '',
                                                       'Folder': '',
                                                       'RootRT': '',
                                                       'RootTT': ''}
                                          }
                         }

TRANSLATOR_MAPPINGS = {'#Alias': 'alias.translator.source.m-at',
                       '#DataDef': 'datadef.translator.source.m-at',
                       '#ImportExport': 'importexport.translator.source.m-at',
                       '#Include': 'include.translator.source.m-at',
                       '#Locals': 'local.translator.source.m-at',
                       '#Magic': 'magic.translator.source.m-at',
                       '#Screen': 'screen.translator.source.m-at',
                       '#ScreenComponent': 'screencomponent.translator.source.m-at',
                       '#ScreenRecord': 'screenrecord.translator.source.m-at',
                       '#ScreenPage': 'screenpage.translator.source.m-at',
                       'other': 'other.translator.source.m-at'
                       }

TRANSLATOR_SEPARATOR = '//------------------------------------------------------------------------------'

SYSTEM_VARIABLES = ("AboutBoxProgram",
                    "AccessLocalData",
                    "ANPTimeServer",
                    "AppCallbackExternalSub",
                    "AuditCode",
                    "AuditExternalSub",
                    "AuditProcessOff",
                    "AuditReadOff",
                    "AuditReadOn",
                    "AuditWriteOff",
                    "AuditWriteOn",
                    "BaseWindowSize",
                    "Client",
                    "ClientType",
                    "CodeUpdateRequired",
                    "CurrentProgram",
                    "DataDefProgram",
                    "DisableClientMessaging",
                    "DisableDataCache",
                    "DisableObjectLogging",
                    "DisableTransactionProcessing",
                    "DisconnectedSuffix",
                    "EmailProgram",
                    "EmulatedUser",
                    "ErrorProcess",
                    "Font",
                    "GlobalScreenStylesProgram",
                    "GlobalWebStylesProgram",
                    "HCIS",
                    "HelpProgram",
                    "MastScanServer",
                    "MaximizeExtraLargeWindow",
                    "MeditorLinkExternalSub",
                    "MeditorPrintExternalSub",
                    "OverrideClientName",
                    "Palette",
                    "PrintPrefProgram",
                    "PrintScrnProgram",
                    "ProcessControlledBy",
                    "ProcessGroup",
                    "ProcessIcon",
                    "ProcessMessage",
                    "PropertiesBoxProgram",
                    "ReferencesProgram",
                    "ReservedFilenameConversion",
                    "RetainErrorTrap",
                    "RingIndexType",
                    "RingSystemOIDBucketing",
                    "RootAccessViolationExternalSub",
                    "ServerCurrentRecordFilteringDisabled",
                    "SessionTempEncryptionOff",
                    "ShiftF4Program",
                    "ShowScreenDelayTimes",
                    "SignonUserMnemonic",
                    "SignonUserName",
                    "SpyExternalSub",
                    "SuppressHoverPointer",
                    "SuspendProgram",
                    "TimeInProgram",
                    "Timeout",
                    "TimeoutProgram",
                    "UnvIndexType",
                    "UnvSystemOIDBucketing",
                    "UserMnemonic",
                    "UserName",
                    "ViewOnlyMode",
                    "WebValidationProgram",
                    "WindowTitleSuffixExternalSub")